// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleGax

/// ConsumerProcurementService allows customers to make purchases of products
/// served by the Cloud Commerce platform.
///
///
/// When purchases are made, the
/// [ConsumerProcurementService][google.cloud.commerce.consumer.procurement.v1.ConsumerProcurementService]
/// programs the appropriate backends, including both Google's own
/// infrastructure, as well as third-party systems, and to enable billing setup
/// for charging for the procured item.
///
///
/// [google.cloud.commerce.consumer.procurement.v1.ConsumerProcurementService]: <doc:ConsumerProcurementServiceClient>
///
/// @Snippet(path: "ConsumerProcurementServiceQuickstart")
public final class ConsumerProcurementServiceClient: Clients.ConsumerProcurementServiceProtocol,
  Sendable
{
  let inner: any Clients.ConsumerProcurementServiceStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.PollingBackoffPolicy

  /// Creates a new `ConsumerProcurementServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.ConsumerProcurementServiceStub =
      try Clients.ConsumerProcurementServiceTransport(options)
    inner = Clients.ConsumerProcurementServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ConsumerProcurementServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Creates a new [Order][google.cloud.commerce.consumer.procurement.v1.Order].
  ///
  /// This API only supports GCP spend-based committed use
  /// discounts specified by GCP documentation.
  ///
  /// The returned long-running operation is in-progress until the backend
  /// completes the creation of the resource. Once completed, the order is
  /// in
  /// [OrderState.ORDER_STATE_ACTIVE][google.cloud.commerce.consumer.procurement.v1.OrderState.ORDER_STATE_ACTIVE].
  /// In case of failure, the order resource will be removed.
  ///
  /// [google.cloud.commerce.consumer.procurement.v1.Order]: <doc:Order>
  ///
  /// @Snippet(path: "ConsumerProcurementService_PlaceOrder")
  public func placeOrder(
    request: PlaceOrderRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.placeOrder(request: request, options: options)
  }

  /// Creates a new [Order][google.cloud.commerce.consumer.procurement.v1.Order].
  ///
  /// This API only supports GCP spend-based committed use
  /// discounts specified by GCP documentation.
  ///
  /// The returned long-running operation is in-progress until the backend
  /// completes the creation of the resource. Once completed, the order is
  /// in
  /// [OrderState.ORDER_STATE_ACTIVE][google.cloud.commerce.consumer.procurement.v1.OrderState.ORDER_STATE_ACTIVE].
  /// In case of failure, the order resource will be removed.
  ///
  /// [google.cloud.commerce.consumer.procurement.v1.Order]: <doc:Order>
  ///
  /// @Snippet(path: "ConsumerProcurementService_PlaceOrder")
  public func placeOrderPollingUntilDone(
    request: PlaceOrderRequest, options: GoogleGax.RequestOptions
  ) async throws -> Order {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Order>.State in
      return try op._extractStatus(Order.self)
    }
    let rawOp = try await self.placeOrder(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Order>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Returns the requested
  /// [Order][google.cloud.commerce.consumer.procurement.v1.Order] resource.
  ///
  /// [google.cloud.commerce.consumer.procurement.v1.Order]: <doc:Order>
  ///
  /// @Snippet(path: "ConsumerProcurementService_GetOrder")
  public func getOrder(
    request: GetOrderRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudCommerceConsumerProcurementV1.Order {
    try await self.inner.getOrder(request: request, options: options)
  }

  /// Lists [Order][google.cloud.commerce.consumer.procurement.v1.Order]
  /// resources that the user has access to, within the scope of the parent
  /// resource.
  ///
  /// [google.cloud.commerce.consumer.procurement.v1.Order]: <doc:Order>
  ///
  /// @Snippet(path: "ConsumerProcurementService_ListOrders")
  public func listOrders(
    request: ListOrdersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudCommerceConsumerProcurementV1.ListOrdersResponse {
    try await self.inner.listOrders(request: request, options: options)
  }

  /// Modifies an existing
  /// [Order][google.cloud.commerce.consumer.procurement.v1.Order] resource.
  ///
  /// [google.cloud.commerce.consumer.procurement.v1.Order]: <doc:Order>
  ///
  /// @Snippet(path: "ConsumerProcurementService_ModifyOrder")
  public func modifyOrder(
    request: ModifyOrderRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.modifyOrder(request: request, options: options)
  }

  /// Modifies an existing
  /// [Order][google.cloud.commerce.consumer.procurement.v1.Order] resource.
  ///
  /// [google.cloud.commerce.consumer.procurement.v1.Order]: <doc:Order>
  ///
  /// @Snippet(path: "ConsumerProcurementService_ModifyOrder")
  public func modifyOrderPollingUntilDone(
    request: ModifyOrderRequest, options: GoogleGax.RequestOptions
  ) async throws -> Order {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Order>.State in
      return try op._extractStatus(Order.self)
    }
    let rawOp = try await self.modifyOrder(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Order>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Cancels an existing
  /// [Order][google.cloud.commerce.consumer.procurement.v1.Order]. Every product
  /// procured in the Order will be cancelled.
  ///
  /// [google.cloud.commerce.consumer.procurement.v1.Order]: <doc:Order>
  ///
  /// @Snippet(path: "ConsumerProcurementService_CancelOrder")
  public func cancelOrder(
    request: CancelOrderRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.cancelOrder(request: request, options: options)
  }

  /// Cancels an existing
  /// [Order][google.cloud.commerce.consumer.procurement.v1.Order]. Every product
  /// procured in the Order will be cancelled.
  ///
  /// [google.cloud.commerce.consumer.procurement.v1.Order]: <doc:Order>
  ///
  /// @Snippet(path: "ConsumerProcurementService_CancelOrder")
  public func cancelOrderPollingUntilDone(
    request: CancelOrderRequest, options: GoogleGax.RequestOptions
  ) async throws -> Order {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Order>.State in
      return try op._extractStatus(Order.self)
    }
    let rawOp = try await self.cancelOrder(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Order>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ConsumerProcurementService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ConsumerProcurementServiceClient`.
  ///
  /// To mock `ConsumerProcurementServiceClient` change your functions to receive
  /// `some ConsumerProcurementServiceProtocol` or `any ConsumerProcurementServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ConsumerProcurementServiceProtocol: Sendable {
    /// See `ConsumerProcurementServiceClient.placeOrder`.
    func placeOrder(
      request: PlaceOrderRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ConsumerProcurementServiceClient.placeOrder`.
    func placeOrderPollingUntilDone(
      request: PlaceOrderRequest, options: GoogleGax.RequestOptions
    ) async throws -> Order

    /// See `ConsumerProcurementServiceClient.getOrder`.
    func getOrder(
      request: GetOrderRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudCommerceConsumerProcurementV1.Order

    /// See `ConsumerProcurementServiceClient.listOrders`.
    func listOrders(
      request: ListOrdersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudCommerceConsumerProcurementV1.ListOrdersResponse

    /// See `ConsumerProcurementServiceClient.modifyOrder`.
    func modifyOrder(
      request: ModifyOrderRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ConsumerProcurementServiceClient.modifyOrder`.
    func modifyOrderPollingUntilDone(
      request: ModifyOrderRequest, options: GoogleGax.RequestOptions
    ) async throws -> Order

    /// See `ConsumerProcurementServiceClient.cancelOrder`.
    func cancelOrder(
      request: CancelOrderRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ConsumerProcurementServiceClient.cancelOrder`.
    func cancelOrderPollingUntilDone(
      request: CancelOrderRequest, options: GoogleGax.RequestOptions
    ) async throws -> Order
  }
}

// Default implementations
extension Clients.ConsumerProcurementServiceProtocol {
  public func placeOrder(request: PlaceOrderRequest) async throws -> GoogleLongRunning.Operation {
    try await self.placeOrder(request: request, options: .init())
  }

  public func placeOrder(
    request: PlaceOrderRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func placeOrderPollingUntilDone(request: PlaceOrderRequest) async throws -> Order {
    return try await self.placeOrderPollingUntilDone(request: request, options: .init())
  }

  public func placeOrderPollingUntilDone(
    request: PlaceOrderRequest, options: GoogleGax.RequestOptions
  ) async throws -> Order {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOrder(request: GetOrderRequest) async throws
    -> GoogleCloudCommerceConsumerProcurementV1.Order
  {
    try await self.getOrder(request: request, options: .init())
  }

  public func getOrder(
    request: GetOrderRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudCommerceConsumerProcurementV1.Order {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOrder(
    name: Swift.String,
  ) async throws -> GoogleCloudCommerceConsumerProcurementV1.Order {
    let request = GetOrderRequest().with {
      $0.name = name
    }
    return try await self.getOrder(request: request)
  }

  public func listOrders(request: ListOrdersRequest) async throws
    -> GoogleCloudCommerceConsumerProcurementV1.ListOrdersResponse
  {
    try await self.listOrders(request: request, options: .init())
  }

  public func listOrders(
    request: ListOrdersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudCommerceConsumerProcurementV1.ListOrdersResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOrdersByItems(
    request: ListOrdersRequest
  ) -> some AsyncSequence<Order, Swift.Error> & Sendable {
    self.listOrdersByItems(request: request, options: .init())
  }

  /// Lists [Order][google.cloud.commerce.consumer.procurement.v1.Order]
  /// resources that the user has access to, within the scope of the parent
  /// resource.
  ///
  /// [google.cloud.commerce.consumer.procurement.v1.Order]: <doc:Order>
  ///
  /// @Snippet(path: "ConsumerProcurementService_ListOrders")
  public func listOrdersByItems(
    request: ListOrdersRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<Order, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudCommerceConsumerProcurementV1.ListOrdersResponse in
      var request = request
      request.pageToken = token
      return try await self.listOrders(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listOrdersByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<Order, Swift.Error> & Sendable {
    let request = ListOrdersRequest().with {
      $0.parent = parent
    }
    return self.listOrdersByItems(request: request)
  }

  public func modifyOrder(request: ModifyOrderRequest) async throws -> GoogleLongRunning.Operation {
    try await self.modifyOrder(request: request, options: .init())
  }

  public func modifyOrder(
    request: ModifyOrderRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func modifyOrderPollingUntilDone(request: ModifyOrderRequest) async throws -> Order {
    return try await self.modifyOrderPollingUntilDone(request: request, options: .init())
  }

  public func modifyOrderPollingUntilDone(
    request: ModifyOrderRequest, options: GoogleGax.RequestOptions
  ) async throws -> Order {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOrder(request: CancelOrderRequest) async throws -> GoogleLongRunning.Operation {
    try await self.cancelOrder(request: request, options: .init())
  }

  public func cancelOrder(
    request: CancelOrderRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOrderPollingUntilDone(request: CancelOrderRequest) async throws -> Order {
    return try await self.cancelOrderPollingUntilDone(request: request, options: .init())
  }

  public func cancelOrderPollingUntilDone(
    request: CancelOrderRequest, options: GoogleGax.RequestOptions
  ) async throws -> Order {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
