// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A licensed user.
public struct LicensedUser: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Username.
  /// Format: `name@domain.com`.
  public var username: Swift.String = Swift.String()

  /// Output only. Timestamp when the license was assigned.
  public var assignTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Timestamp when the license was recently used. This may not be
  /// the most recent usage time, and will be updated regularly (within 24
  /// hours).
  public var recentUsageTime: GoogleWKT.WKTTimestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `LicensedUser`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LicensedUser().with { $0.username = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let username = CodingKeys(stringValue: "username")
    static let assignTime = CodingKeys(stringValue: "assignTime")
    static let recentUsageTime = CodingKeys(stringValue: "recentUsageTime")

    static let _knownKeys: Set<Swift.String> = [
      "username",
      "assignTime",
      "recentUsageTime",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .username) {
      self.username = value
    }
    self.assignTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .assignTime)
    self.recentUsageTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .recentUsageTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.username, forKey: .username)
    try container.encodeIfPresent(self.assignTime, forKey: .assignTime)
    try container.encodeIfPresent(self.recentUsageTime, forKey: .recentUsageTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.commerce.consumer.procurement.v1.LicensedUser"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
