// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Service for managing licenses.
///
/// @Snippet(path: "LicenseManagementServiceQuickstart")
public final class LicenseManagementServiceClient: Clients.LicenseManagementServiceProtocol,
  Sendable
{
  let inner: any Clients.LicenseManagementServiceStub

  /// Creates a new `LicenseManagementServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.LicenseManagementServiceStub =
      try Clients.LicenseManagementServiceTransport(options)
    inner = Clients.LicenseManagementServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.LicenseManagementServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Gets the license pool.
  ///
  /// @Snippet(path: "LicenseManagementService_GetLicensePool")
  public func getLicensePool(
    request: GetLicensePoolRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudCommerceConsumerProcurementV1.LicensePool {
    try await self.inner.getLicensePool(request: request, options: options)
  }

  /// Updates the license pool if one exists for this Order.
  ///
  /// @Snippet(path: "LicenseManagementService_UpdateLicensePool")
  public func updateLicensePool(
    request: UpdateLicensePoolRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudCommerceConsumerProcurementV1.LicensePool {
    try await self.inner.updateLicensePool(request: request, options: options)
  }

  /// Assigns a license to a user.
  ///
  /// @Snippet(path: "LicenseManagementService_Assign")
  public func assign(
    request: AssignRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudCommerceConsumerProcurementV1.AssignResponse {
    try await self.inner.assign(request: request, options: options)
  }

  /// Unassigns a license from a user.
  ///
  /// @Snippet(path: "LicenseManagementService_Unassign")
  public func unassign(
    request: UnassignRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudCommerceConsumerProcurementV1.UnassignResponse {
    try await self.inner.unassign(request: request, options: options)
  }

  /// Enumerates all users assigned a license.
  ///
  /// @Snippet(path: "LicenseManagementService_EnumerateLicensedUsers")
  public func enumerateLicensedUsers(
    request: EnumerateLicensedUsersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudCommerceConsumerProcurementV1.EnumerateLicensedUsersResponse {
    try await self.inner.enumerateLicensedUsers(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "LicenseManagementService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `LicenseManagementServiceClient`.
  ///
  /// To mock `LicenseManagementServiceClient` change your functions to receive
  /// `some LicenseManagementServiceProtocol` or `any LicenseManagementServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol LicenseManagementServiceProtocol: Sendable {
    /// See `LicenseManagementServiceClient.getLicensePool`.
    func getLicensePool(
      request: GetLicensePoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudCommerceConsumerProcurementV1.LicensePool

    /// See `LicenseManagementServiceClient.updateLicensePool`.
    func updateLicensePool(
      request: UpdateLicensePoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudCommerceConsumerProcurementV1.LicensePool

    /// See `LicenseManagementServiceClient.assign`.
    func assign(
      request: AssignRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudCommerceConsumerProcurementV1.AssignResponse

    /// See `LicenseManagementServiceClient.unassign`.
    func unassign(
      request: UnassignRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudCommerceConsumerProcurementV1.UnassignResponse

    /// See `LicenseManagementServiceClient.enumerateLicensedUsers`.
    func enumerateLicensedUsers(
      request: EnumerateLicensedUsersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudCommerceConsumerProcurementV1.EnumerateLicensedUsersResponse
  }
}

// Default implementations
extension Clients.LicenseManagementServiceProtocol {
  public func getLicensePool(request: GetLicensePoolRequest) async throws
    -> GoogleCloudCommerceConsumerProcurementV1.LicensePool
  {
    try await self.getLicensePool(request: request, options: .init())
  }

  public func getLicensePool(
    request: GetLicensePoolRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudCommerceConsumerProcurementV1.LicensePool {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getLicensePool(
    name: Swift.String,
  ) async throws -> GoogleCloudCommerceConsumerProcurementV1.LicensePool {
    let request = GetLicensePoolRequest().with {
      $0.name = name
    }
    return try await self.getLicensePool(request: request)
  }

  public func updateLicensePool(request: UpdateLicensePoolRequest) async throws
    -> GoogleCloudCommerceConsumerProcurementV1.LicensePool
  {
    try await self.updateLicensePool(request: request, options: .init())
  }

  public func updateLicensePool(
    request: UpdateLicensePoolRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudCommerceConsumerProcurementV1.LicensePool {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateLicensePool(
    licensePool: LicensePool?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> GoogleCloudCommerceConsumerProcurementV1.LicensePool {
    let request = UpdateLicensePoolRequest().with {
      $0.licensePool = licensePool
      $0.updateMask = updateMask
    }
    return try await self.updateLicensePool(request: request)
  }

  public func assign(request: AssignRequest) async throws
    -> GoogleCloudCommerceConsumerProcurementV1.AssignResponse
  {
    try await self.assign(request: request, options: .init())
  }

  public func assign(
    request: AssignRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudCommerceConsumerProcurementV1.AssignResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func assign(
    parent: Swift.String,
    usernames: [Swift.String],
  ) async throws -> GoogleCloudCommerceConsumerProcurementV1.AssignResponse {
    let request = AssignRequest().with {
      $0.parent = parent
      $0.usernames = usernames
    }
    return try await self.assign(request: request)
  }

  public func unassign(request: UnassignRequest) async throws
    -> GoogleCloudCommerceConsumerProcurementV1.UnassignResponse
  {
    try await self.unassign(request: request, options: .init())
  }

  public func unassign(
    request: UnassignRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudCommerceConsumerProcurementV1.UnassignResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func unassign(
    parent: Swift.String,
    usernames: [Swift.String],
  ) async throws -> GoogleCloudCommerceConsumerProcurementV1.UnassignResponse {
    let request = UnassignRequest().with {
      $0.parent = parent
      $0.usernames = usernames
    }
    return try await self.unassign(request: request)
  }

  public func enumerateLicensedUsers(request: EnumerateLicensedUsersRequest) async throws
    -> GoogleCloudCommerceConsumerProcurementV1.EnumerateLicensedUsersResponse
  {
    try await self.enumerateLicensedUsers(request: request, options: .init())
  }

  public func enumerateLicensedUsers(
    request: EnumerateLicensedUsersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudCommerceConsumerProcurementV1.EnumerateLicensedUsersResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func enumerateLicensedUsersByItems(
    request: EnumerateLicensedUsersRequest
  ) -> some AsyncSequence<LicensedUser, any Swift.Error> & Sendable {
    self.enumerateLicensedUsersByItems(request: request, options: .init())
  }

  /// Enumerates all users assigned a license.
  ///
  /// @Snippet(path: "LicenseManagementService_EnumerateLicensedUsers")
  public func enumerateLicensedUsersByItems(
    request: EnumerateLicensedUsersRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<LicensedUser, any Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudCommerceConsumerProcurementV1.EnumerateLicensedUsersResponse in
      var request = request
      request.pageToken = token
      return try await self.enumerateLicensedUsers(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func enumerateLicensedUsersByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<LicensedUser, any Swift.Error> & Sendable {
    let request = EnumerateLicensedUsersRequest().with {
      $0.parent = parent
    }
    return self.enumerateLicensedUsersByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
