// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A license pool represents a pool of licenses that can be assigned to users.
public struct LicensePool: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. Format:
  /// `billingAccounts/{billing_account}/orders/{order}/licensePool`
  public var name: Swift.String = Swift.String()

  /// Required. Assignment protocol for the license pool.
  public var licenseAssignmentProtocol: AssignmentProtocol? = nil

  /// Output only. Licenses count that are available to be assigned.
  public var availableLicenseCount: Swift.Int32 = Swift.Int32()

  /// Output only. Total number of licenses in the pool.
  public var totalLicenseCount: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `LicensePool`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LicensePool().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let licenseAssignmentProtocol = CodingKeys(stringValue: "licenseAssignmentProtocol")
    static let availableLicenseCount = CodingKeys(stringValue: "availableLicenseCount")
    static let totalLicenseCount = CodingKeys(stringValue: "totalLicenseCount")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "licenseAssignmentProtocol",
      "availableLicenseCount",
      "totalLicenseCount",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.licenseAssignmentProtocol = try container.decodeIfPresent(
      AssignmentProtocol.self, forKey: .licenseAssignmentProtocol)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .availableLicenseCount) {
      self.availableLicenseCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .totalLicenseCount) {
      self.totalLicenseCount = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(
      self.licenseAssignmentProtocol, forKey: .licenseAssignmentProtocol)
    try container.encode(self.availableLicenseCount, forKey: .availableLicenseCount)
    try container.encode(self.totalLicenseCount, forKey: .totalLicenseCount)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.commerce.consumer.procurement.v1.LicensePool"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
