// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// State of a change.
///
/// - Note: Adding cases to this enumeration is not considered a breaking change.
///   Always include an `@unknown default:` case when switching over this type.
///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
///   expecting specific values to remain unparsed; future releases may promote
///   them to named cases.
public enum LineItemChangeState: Codable, Equatable, Hashable, Sendable {
  /// Sentinel value. Do not use.
  case unspecified
  /// Change is in this state when a change is initiated and waiting for partner
  /// approval. This state is only applicable for pending change.
  case pendingApproval
  /// Change is in this state after it's approved by the partner or auto-approved
  /// but before it takes effect. The change can be overwritten or cancelled
  /// depending on the new line item info property (pending Private Offer change
  /// cannot be cancelled and can only be overwritten by another Private Offer).
  /// This state is only applicable for pending change.
  case approved
  /// Change is in this state after it's been activated. This state is only
  /// applicable for change in history.
  case completed
  /// Change is in this state if it was rejected by the partner. This state is
  /// only applicable for change in history.
  case rejected
  /// Change is in this state if it was abandoned by the user. This state is only
  /// applicable for change in history.
  case abandoned
  /// Change is in this state if it's currently being provisioned downstream. The
  /// change can't be overwritten or cancelled when it's in this state. This
  /// state is only applicable for pending change.
  case activating
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific integer values in this case;
  ///   future releases may promote them to named enum cases.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific string literals in this case;
  ///   future releases may promote them to named enum cases.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .pendingApproval: return 1
    case .approved: return 2
    case .completed: return 3
    case .rejected: return 4
    case .abandoned: return 5
    case .activating: return 6
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "LINE_ITEM_CHANGE_STATE_UNSPECIFIED"
    case .pendingApproval: return "LINE_ITEM_CHANGE_STATE_PENDING_APPROVAL"
    case .approved: return "LINE_ITEM_CHANGE_STATE_APPROVED"
    case .completed: return "LINE_ITEM_CHANGE_STATE_COMPLETED"
    case .rejected: return "LINE_ITEM_CHANGE_STATE_REJECTED"
    case .abandoned: return "LINE_ITEM_CHANGE_STATE_ABANDONED"
    case .activating: return "LINE_ITEM_CHANGE_STATE_ACTIVATING"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:LineItemChangeState/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "LINE_ITEM_CHANGE_STATE_UNSPECIFIED": self = .unspecified
    case "LINE_ITEM_CHANGE_STATE_PENDING_APPROVAL": self = .pendingApproval
    case "LINE_ITEM_CHANGE_STATE_APPROVED": self = .approved
    case "LINE_ITEM_CHANGE_STATE_COMPLETED": self = .completed
    case "LINE_ITEM_CHANGE_STATE_REJECTED": self = .rejected
    case "LINE_ITEM_CHANGE_STATE_ABANDONED": self = .abandoned
    case "LINE_ITEM_CHANGE_STATE_ACTIVATING": self = .activating
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:LineItemChangeState/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .pendingApproval
    case 2: self = .approved
    case 3: self = .completed
    case 4: self = .rejected
    case 5: self = .abandoned
    case 6: self = .activating
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode("LINE_ITEM_CHANGE_STATE_UNSPECIFIED")
    case .pendingApproval: return try container.encode("LINE_ITEM_CHANGE_STATE_PENDING_APPROVAL")
    case .approved: return try container.encode("LINE_ITEM_CHANGE_STATE_APPROVED")
    case .completed: return try container.encode("LINE_ITEM_CHANGE_STATE_COMPLETED")
    case .rejected: return try container.encode("LINE_ITEM_CHANGE_STATE_REJECTED")
    case .abandoned: return try container.encode("LINE_ITEM_CHANGE_STATE_ABANDONED")
    case .activating: return try container.encode("LINE_ITEM_CHANGE_STATE_ACTIVATING")
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
