// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A change made on a line item.
public struct LineItemChange: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Change ID.
  /// All changes made within one order update operation have the same change_id.
  public var changeId: Swift.String = Swift.String()

  /// Required. Type of the change to make.
  public var changeType: LineItemChangeType = LineItemChangeType()

  /// Output only. Line item info before the change.
  public var oldLineItemInfo: LineItemInfo? = nil

  /// Line item info after the change.
  public var newLineItemInfo: LineItemInfo? = nil

  /// Output only. State of the change.
  public var changeState: LineItemChangeState = LineItemChangeState()

  /// Output only. Provider-supplied message explaining the LineItemChange's
  /// state. Mainly used to communicate progress and ETA for provisioning in the
  /// case of `PENDING_APPROVAL`, and to explain why the change request was
  /// denied or canceled in the case of `REJECTED` and `CANCELED` states.
  public var stateReason: Swift.String = Swift.String()

  /// Output only. Predefined enum types for why this line item change is in
  /// current state. For example, a line item change's state could be
  /// `LINE_ITEM_CHANGE_STATE_COMPLETED` because of end-of-term expiration,
  /// immediate cancellation initiated by the user, or system-initiated
  /// cancellation.
  public var changeStateReasonType: LineItemChangeStateReasonType = LineItemChangeStateReasonType()

  /// Output only. A time at which the change became or will become (in case of
  /// pending change) effective.
  public var changeEffectiveTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time when change was initiated.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time when change was updated, e.g. approved/rejected by
  /// partners or cancelled by the user.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `LineItemChange`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LineItemChange().with { $0.changeId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let changeId = CodingKeys(stringValue: "changeId")
    static let changeType = CodingKeys(stringValue: "changeType")
    static let oldLineItemInfo = CodingKeys(stringValue: "oldLineItemInfo")
    static let newLineItemInfo = CodingKeys(stringValue: "newLineItemInfo")
    static let changeState = CodingKeys(stringValue: "changeState")
    static let stateReason = CodingKeys(stringValue: "stateReason")
    static let changeStateReasonType = CodingKeys(stringValue: "changeStateReasonType")
    static let changeEffectiveTime = CodingKeys(stringValue: "changeEffectiveTime")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")

    static let _knownKeys: Set<Swift.String> = [
      "changeId",
      "changeType",
      "oldLineItemInfo",
      "newLineItemInfo",
      "changeState",
      "stateReason",
      "changeStateReasonType",
      "changeEffectiveTime",
      "createTime",
      "updateTime",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .changeId) {
      self.changeId = value
    }
    if let value = try container.decodeIfPresent(LineItemChangeType.self, forKey: .changeType) {
      self.changeType = value
    }
    self.oldLineItemInfo = try container.decodeIfPresent(
      LineItemInfo.self, forKey: .oldLineItemInfo)
    self.newLineItemInfo = try container.decodeIfPresent(
      LineItemInfo.self, forKey: .newLineItemInfo)
    if let value = try container.decodeIfPresent(LineItemChangeState.self, forKey: .changeState) {
      self.changeState = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .stateReason) {
      self.stateReason = value
    }
    if let value = try container.decodeIfPresent(
      LineItemChangeStateReasonType.self, forKey: .changeStateReasonType)
    {
      self.changeStateReasonType = value
    }
    self.changeEffectiveTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .changeEffectiveTime)
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.changeId, forKey: .changeId)
    try container.encode(self.changeType, forKey: .changeType)
    try container.encodeIfPresent(self.oldLineItemInfo, forKey: .oldLineItemInfo)
    try container.encodeIfPresent(self.newLineItemInfo, forKey: .newLineItemInfo)
    try container.encode(self.changeState, forKey: .changeState)
    try container.encode(self.stateReason, forKey: .stateReason)
    try container.encode(self.changeStateReasonType, forKey: .changeStateReasonType)
    try container.encodeIfPresent(self.changeEffectiveTime, forKey: .changeEffectiveTime)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.commerce.consumer.procurement.v1.LineItemChange"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
