// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A single item within an order.
public struct LineItem: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Line item ID.
  public var lineItemId: Swift.String = Swift.String()

  /// Output only. Current state and information of this item. It tells what,
  /// e.g. which offer, is currently effective.
  public var lineItemInfo: LineItemInfo? = nil

  /// Output only. A change made on the item which is pending and not yet
  /// effective. Absence of this field indicates the line item is not undergoing
  /// a change.
  public var pendingChange: LineItemChange? = nil

  /// Output only. Changes made on the item that are not pending anymore which
  /// might be because they already took effect, were reverted by the customer,
  /// or were rejected by the partner. No more operations are allowed on these
  /// changes.
  public var changeHistory: [LineItemChange] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `LineItem`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LineItem().with { $0.lineItemId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let lineItemId = CodingKeys(stringValue: "lineItemId")
    static let lineItemInfo = CodingKeys(stringValue: "lineItemInfo")
    static let pendingChange = CodingKeys(stringValue: "pendingChange")
    static let changeHistory = CodingKeys(stringValue: "changeHistory")

    static let _knownKeys: Set<Swift.String> = [
      "lineItemId",
      "lineItemInfo",
      "pendingChange",
      "changeHistory",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .lineItemId) {
      self.lineItemId = value
    }
    self.lineItemInfo = try container.decodeIfPresent(LineItemInfo.self, forKey: .lineItemInfo)
    self.pendingChange = try container.decodeIfPresent(LineItemChange.self, forKey: .pendingChange)
    if let value = try container.decodeIfPresent([LineItemChange].self, forKey: .changeHistory) {
      self.changeHistory = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.lineItemId, forKey: .lineItemId)
    try container.encodeIfPresent(self.lineItemInfo, forKey: .lineItemInfo)
    try container.encodeIfPresent(self.pendingChange, forKey: .pendingChange)
    try container.encode(self.changeHistory, forKey: .changeHistory)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.commerce.consumer.procurement.v1.LineItem"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
