// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Type of a line item change.
///
/// - Note: Adding cases to this enumeration is not considered a breaking change.
///   Always include an `@unknown default:` case when switching over this type.
///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
///   expecting specific values to remain unparsed; future releases may promote
///   them to named cases.
public enum LineItemChangeType: Codable, Equatable, Hashable, Sendable {
  /// Sentinel value. Do not use.
  case unspecified
  /// The change is to create a new line item.
  case create
  /// The change is to update an existing line item.
  case update
  /// The change is to cancel an existing line item.
  case cancel
  /// The change is to revert a cancellation.
  case revertCancellation
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific integer values in this case;
  ///   future releases may promote them to named enum cases.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific string literals in this case;
  ///   future releases may promote them to named enum cases.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .create: return 1
    case .update: return 2
    case .cancel: return 3
    case .revertCancellation: return 4
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "LINE_ITEM_CHANGE_TYPE_UNSPECIFIED"
    case .create: return "LINE_ITEM_CHANGE_TYPE_CREATE"
    case .update: return "LINE_ITEM_CHANGE_TYPE_UPDATE"
    case .cancel: return "LINE_ITEM_CHANGE_TYPE_CANCEL"
    case .revertCancellation: return "LINE_ITEM_CHANGE_TYPE_REVERT_CANCELLATION"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:LineItemChangeType/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "LINE_ITEM_CHANGE_TYPE_UNSPECIFIED": self = .unspecified
    case "LINE_ITEM_CHANGE_TYPE_CREATE": self = .create
    case "LINE_ITEM_CHANGE_TYPE_UPDATE": self = .update
    case "LINE_ITEM_CHANGE_TYPE_CANCEL": self = .cancel
    case "LINE_ITEM_CHANGE_TYPE_REVERT_CANCELLATION": self = .revertCancellation
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:LineItemChangeType/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .create
    case 2: self = .update
    case 3: self = .cancel
    case 4: self = .revertCancellation
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode("LINE_ITEM_CHANGE_TYPE_UNSPECIFIED")
    case .create: return try container.encode("LINE_ITEM_CHANGE_TYPE_CREATE")
    case .update: return try container.encode("LINE_ITEM_CHANGE_TYPE_UPDATE")
    case .cancel: return try container.encode("LINE_ITEM_CHANGE_TYPE_CANCEL")
    case .revertCancellation:
      return try container.encode("LINE_ITEM_CHANGE_TYPE_REVERT_CANCELLATION")
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
