// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// User-provided Parameters.
public struct Parameter: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Name of the parameter.
  public var name: Swift.String = Swift.String()

  /// Value of parameter.
  public var value: Parameter.Value? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Parameter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Parameter().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let value = CodingKeys(stringValue: "value")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "value",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.value = try container.decodeIfPresent(Parameter.Value.self, forKey: .value)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.value, forKey: .value)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public struct Value: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The kind of value.
    public var kind: KindOneOf? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Value`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Value().with { $0.int64Value = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let int64Value = CodingKeys(stringValue: "int64Value")
      static let stringValue = CodingKeys(stringValue: "stringValue")
      static let doubleValue = CodingKeys(stringValue: "doubleValue")

      static let _knownKeys: Set<Swift.String> = [
        "int64Value",
        "stringValue",
        "doubleValue",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var kind: KindOneOf? = nil
      let kindCheckAndSet = {
        if kind != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'kind'"))
        }
        kind = $0
      }
      if let int64Value = try container.decodeIfPresent(Swift.Int64.self, forKey: .int64Value) {
        try kindCheckAndSet(.int64Value(int64Value))
      }
      if let stringValue = try container.decodeIfPresent(Swift.String.self, forKey: .stringValue) {
        try kindCheckAndSet(.stringValue(stringValue))
      }
      if let doubleValue = try container.decodeIfPresent(Swift.Double.self, forKey: .doubleValue) {
        try kindCheckAndSet(.doubleValue(doubleValue))
      }
      self.kind = kind
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.kind {
        switch choice {
        case .int64Value(let value):
          try container.encode(value, forKey: .int64Value)
        case .stringValue(let value):
          try container.encode(value, forKey: .stringValue)
        case .doubleValue(let value):
          try container.encode(value, forKey: .doubleValue)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The kind of value.
    public enum KindOneOf: Codable, Equatable, Sendable {
      /// Represents an int64 value.
      case int64Value(Swift.Int64)
      /// Represents a string value.
      case stringValue(Swift.String)
      /// Represents a double value.
      case doubleValue(Swift.Double)
    }

    /// The type URL for `Value`: `"type.googleapis.com/google.cloud.commerce.consumer.procurement.v1.Parameter.Value"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.commerce.consumer.procurement.v1.Parameter.Value"
    }

    /// Initialize an instance of `Value` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.commerce.consumer.procurement.v1.Parameter.Value"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `Value` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The type URL for `Parameter`: `"type.googleapis.com/google.cloud.commerce.consumer.procurement.v1.Parameter"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.commerce.consumer.procurement.v1.Parameter"
  }

  /// Initialize an instance of `Parameter` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.commerce.consumer.procurement.v1.Parameter"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `Parameter` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
