// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for
/// [ConsumerProcurementService.PlaceOrder][google.cloud.commerce.consumer.procurement.v1.ConsumerProcurementService.PlaceOrder].
///
/// [google.cloud.commerce.consumer.procurement.v1.ConsumerProcurementService.PlaceOrder]: <doc:ConsumerProcurementServiceClient/placeOrder(request:options:)>
public struct PlaceOrderRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the parent resource.
  /// This field has the form  `billingAccounts/{billing-account-id}`.
  public var parent: Swift.String = Swift.String()

  /// Required. The user-specified name of the order being placed.
  public var displayName: Swift.String = Swift.String()

  /// Optional. Places order for offer. Required when an offer-based order is
  /// being placed.
  public var lineItemInfo: [LineItemInfo] = []

  /// Optional. A unique identifier for this request.
  /// The server will ignore subsequent requests that provide a duplicate request
  /// ID for at least 24 hours after the first request.
  ///
  /// The request ID must be a valid
  /// [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier#Format).
  public var requestId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PlaceOrderRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PlaceOrderRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let lineItemInfo = CodingKeys(stringValue: "lineItemInfo")
    static let requestId = CodingKeys(stringValue: "requestId")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "displayName",
      "lineItemInfo",
      "requestId",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent([LineItemInfo].self, forKey: .lineItemInfo) {
      self.lineItemInfo = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .requestId) {
      self.requestId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.lineItemInfo, forKey: .lineItemInfo)
    try container.encode(self.requestId, forKey: .requestId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.commerce.consumer.procurement.v1.PlaceOrderRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
